apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oci-fss-single-pvc-single-pv-different-ns
  namespace: sunmi
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi
  volumeName: oci-fss-single-pv-different-ns