apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oci-fss-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi
  volumeName: oci-fss-pv