apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc-nlb-cluster
  labels:
    app: nginx
  annotations:
    oci.oraclecloud.com/load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: UDP
  selector:
    app: nginx