apiVersion: v1
kind: Pod
metadata:
  name: fss-dynamic-app1-node1
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - name: http
          containerPort: 80
      volumeMounts:
        - name: persistent-storage
          mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: fss-dynamic-claim
  nodeSelector:
    nodeName: worknode1
---
apiVersion: v1
kind: Pod
metadata:
  name: fss-dynamic-app2-node1
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - name: http
          containerPort: 80
      volumeMounts:
        - name: persistent-storage
          mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: fss-dynamic-claim
  nodeSelector:
    nodeName: worknode1
---
apiVersion: v1
kind: Pod
metadata:
  name: fss-dynamic-app1-node3
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - name: http
          containerPort: 80
      volumeMounts:
        - name: persistent-storage
          mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: fss-dynamic-claim
  nodeSelector:
    nodeName: worknode3