apiVersion: v1
kind: Pod
metadata:
  name: oke-fsssinglepod-worknode1
spec:
  containers:
  - name: web
    image: nginx
    volumeMounts:
     - name: oci-nfs
       mountPath: "/usr/share/nginx/html/"
    ports:
      - containerPort: 80
        name: http
  volumes:
  - name: oci-nfs
    persistentVolumeClaim:
      claimName: oci-fss-pvc
      readOnly: false
  nodeSelector:
    nodeName: worknode1